        .cpu    "6502"
        .logical $8000
        .byte   $ea
        .fill   8191,$00
        .here
        .logical $8000
        .fill   8192,$01
        .here
        .logical $8000
        .fill   8192,$02
        .here
        .logical $8000
        .fill   8192,$03
        .here
        .logical $8000
        .fill   8192,$04
        .here
        .logical $8000
        .fill   8192,$05
        .here
        .logical $8000
        .fill   8192,$06
        .here
        .logical $8000
        .fill   8192,$07
        .here
